import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');
const isTablet = width > 768;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5EC',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: width * 0.04,
    paddingVertical: isTablet ? 20 : 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    paddingTop: 48,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: isTablet ? 22 : 18,
    fontWeight: 'bold',
    color: '#333',
  },
  placeholder: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  formContainer: {
    paddingHorizontal: width * 0.04,
    paddingTop: 20,
  },
  inputContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 12,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    overflow: 'hidden',
  },
  iconContainer: {
    position: 'absolute',
    left: 16,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    zIndex: 1,
  },
  input: {
    paddingVertical: isTablet ? 18 : 16,
    paddingLeft: 52,
    paddingRight: 16,
    fontSize: isTablet ? 16 : 14,
    color: '#333',
  },
  inputFull: {
    paddingVertical: isTablet ? 18 : 16,
    paddingHorizontal: 16,
    fontSize: isTablet ? 16 : 14,
    color: '#333',
  },
  textArea: {
    minHeight: 100,
    paddingTop: isTablet ? 18 : 16,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: isTablet ? 16 : 14,
    paddingHorizontal: 16,
    marginTop: 8,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  checkboxLabel: {
    fontSize: isTablet ? 16 : 14,
    color: '#333',
    fontWeight: '500',
    marginLeft: 12,
  },
  mapButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#82b440',
    borderRadius: 12,
    paddingVertical: isTablet ? 16 : 14,
    paddingHorizontal: 16,
    marginTop: 8,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    gap: 8,
  },
  mapButtonText: {
    fontSize: isTablet ? 16 : 14,
    color: '#fff',
    fontWeight: '600',
  },
  selectedAddressContainer: {
    backgroundColor: '#E8F5E9',
    borderRadius: 12,
    padding: 16,
    marginTop: 4,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#82b440',
  },
  selectedAddressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  selectedAddressTitle: {
    fontSize: isTablet ? 15 : 13,
    fontWeight: '600',
    color: '#82b440',
  },
  selectedAddressText: {
    fontSize: isTablet ? 15 : 13,
    color: '#333',
    lineHeight: 20,
  },
  switchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: isTablet ? 16 : 14,
    paddingHorizontal: 16,
    marginTop: 8,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  switchLabel: {
    fontSize: isTablet ? 16 : 14,
    color: '#333',
    fontWeight: '500',
  },
  bottomPadding: {
    height: 100,
  },
  buttonContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    paddingHorizontal: width * 0.04,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  submitButton: {
    backgroundColor: '#8BC34A',
    paddingVertical: isTablet ? 18 : 16,
    borderRadius: 12,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    fontSize: isTablet ? 18 : 16,
    fontWeight: 'bold',
    color: '#fff',
    letterSpacing: 1,
  },
  dropdownWrapper: {
    marginBottom: 12,
  },
  dropdownContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  dropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: isTablet ? 18 : 16,
    paddingHorizontal: 16,
  },
  selectedIconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  selectedIconText: {
    fontSize: isTablet ? 16 : 14,
    color: '#333',
    fontWeight: '500',
  },
  dropdownMenu: {
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: isTablet ? 16 : 14,
    paddingHorizontal: 16,
  },
  dropdownItemActive: {
    backgroundColor: '#E8F5E9',
  },
  dropdownDivider: {
    width: 1,
    height: 24,
    backgroundColor: '#ddd',
    marginHorizontal: 16,
  },
  dropdownItemText: {
    fontSize: isTablet ? 16 : 14,
    color: '#333',
  },
  dropdownItemTextActive: {
    color: '#4A7C59',
    fontWeight: '600',
  },
});
