import { Dimensions, Platform, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { backgroundColor: '#f2f2f2' },
  content: { padding: 10, paddingTop: 48 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  backButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    elevation: 1,
  },
  backText: { fontSize: 16 },
  headerActions: { flexDirection: 'row', gap: 6 },
  iconBtn: {
    marginLeft: 6,
    backgroundColor: '#fff',
    padding: 6,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },

  imageWrapper: {
    width: '100%',
    height: width * 0.6,
    backgroundColor: '#fff',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    position: 'relative',
  },
  productImage: {
    width: '70%',
    height: '65%',
    resizeMode: 'contain',
  },
  arrowLeft: {
    position: 'absolute',
    left: 8,
  },
  arrowRight: {
    position: 'absolute',
    right: 8,
  },

  card: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 10,
    shadowColor: '#000',
    shadowOpacity: 0.03,
    elevation: 2,
  },
  price: { color: '#6aa84f', fontWeight: '700', marginBottom: 6, fontSize: 14, flexWrap: 'wrap' },
  titleRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, flexWrap: 'wrap' },
  title: { fontSize: 15, fontWeight: '700', flexWrap: 'wrap', flex: 1 },
  store: { color: '#666', marginTop: 4, fontSize: 12, flexWrap: 'wrap' },
  heart: { fontSize: 20, marginLeft: 8 },

  infoBox: {
    backgroundColor: '#f7faf7',
    borderRadius: 8,
    padding: 8,
    marginBottom: 10,
  },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between' },
  infoTitle: { color: '#444', fontWeight: '600', fontSize: 12 },
  infoValue: { color: '#333', marginTop: 4, fontSize: 13 },

  quantitySection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  quantityLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  quantityControl: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8f8f8',
    borderRadius: 8,
    padding: 4,
  },
  quantityButton: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 6,
  },
  quantityText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginHorizontal: 20,
    minWidth: 30,
    textAlign: 'center',
  },

  descBlock: { marginTop: 16, height: 225 },
  descTitle: { fontWeight: '700', marginBottom: 6, fontSize: 13 },
  descText: { color: '#333', lineHeight: 18, fontSize: 13 },

  footer: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: Platform.OS === 'ios' ? 16 : 12,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderRadius: 14,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    elevation: 4,
    gap: 10,
  },
  addToCartBtn: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: '#007AFF',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  addToCartText: { 
    color: '#007AFF', 
    fontWeight: '700', 
    fontSize: 15,
  },
  footerBuyBtn: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#82b440',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  buyText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  flyingImage: {
    position: 'absolute',
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
    borderWidth: 2,
    borderColor: '#007AFF',
  },
  flyingImageContent: {
    width: 40,
    height: 40,
  },

  // Bottom Sheet Styles
  sheetOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  quantitySheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 10,
  },
  sheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#ddd',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 8,
  },
  sheetContent: {
    padding: 20,
  },
  sheetTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#333',
    marginBottom: 20,
  },
  sheetProduct: {
    flexDirection: 'row',
    backgroundColor: '#f8f8f8',
    borderRadius: 12,
    padding: 12,
    marginBottom: 20,
  },
  sheetProductImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    backgroundColor: '#fff',
  },
  sheetProductInfo: {
    flex: 1,
    marginLeft: 12,
    justifyContent: 'center',
  },
  sheetProductName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  sheetProductPrice: {
    fontSize: 18,
    fontWeight: '700',
    color: '#82b440',
    marginBottom: 4,
  },
  sheetProductStock: {
    fontSize: 13,
    color: '#666',
  },
  sheetQuantitySection: {
    marginBottom: 24,
  },
  sheetQuantityLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 12,
  },
  sheetQuantityControl: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8f8f8',
    borderRadius: 12,
    padding: 8,
  },
  sheetQuantityButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  sheetQuantityText: {
    fontSize: 22,
    fontWeight: '700',
    color: '#333',
    marginHorizontal: 32,
    minWidth: 40,
    textAlign: 'center',
  },
  sheetFooter: {
    gap: 12,
  },
  sheetTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#f8f8f8',
    borderRadius: 12,
  },
  sheetTotalLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#666',
  },
  sheetTotalAmount: {
    fontSize: 20,
    fontWeight: '700',
    color: '#82b440',
  },
  sheetConfirmButton: {
    backgroundColor: '#82b440',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#82b440',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  sheetConfirmText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
});
